### ISSUE TITLE
US03 Front: Como visitante quiero poder ver en la vista principal, información importante de la aplicación, servicios y funcionalidades.

### ISSUE THREAD

**Issue by yaromvp** [4GeeksAcademy/Proyectofinal-latampt36-Landsquare#5]
- [x] Construir el NavBar
- [x] Diseñar el Body
- [x] Construir el Footer

**Comment by nath1710** [comment]
Se realiza NavBar (se deja como pendiente poner las direcciones para las views Buy Land, Find an Agent y Contact  y en el Footer se agregan los autores del proyecto, queda pendiente colocar las red social de Linkedin  de Yarom
